# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Create JSON
        run: sbt "run ${{ vars.JAM_URL }} ${{ vars.LESS_THAN_DAYS }} ${{ vars.END_DATE }}"
      - uses: actions/upload-artifact@v3
        with:
          name: JSON results for game Jams
          path: ./gameJams.json
